### ISSUE TITLE
Show drop action somewhere

### ISSUE THREAD

**Issue by tobiasKaminsky** [rullzer/nextdrop#4]
Showing the drop option in the headline is maybe too much.
What about showing it within the files app on the left side above the trash bin? 
There could be enough space for the drop field and the generated link.

@rullzer @skjnldsv for discussion :-)

**Comment by rullzer** [comment]
I'm not sure it is that easy to hijack that. as least my css knowledge is a bit limited here. But that sounds cool yes.

**Comment by skjnldsv** [comment]
Its easy to do! :)
You just need to register a new Navigation element (like the trashbin) With the 'pinned' class. Everything will be done automatically (https://docs.nextcloud.com/server/12/developer_manual/design/navigation.html#pinned-entry)

**Comment by tobiasKaminsky** [comment]
Great 👍

**Comment by rullzer** [comment]
Done :)

**Comment by tobiasKaminsky** [comment]
Looks great 👍 

To have it slightly more in sync, you can try to adapt it to this, as it is when sharing on servre:
![image](https://user-images.githubusercontent.com/5836855/33599598-ee92980e-d9a6-11e7-9876-3b8fe45dfa11.png)

**Comment by tobiasKaminsky** [comment]
Somehow this gets sorted on top at my nc12:
![image](https://user-images.githubusercontent.com/5836855/33600027-58b0e42e-d9a8-11e7-98a5-e5e5b8cd3b02.png)

**Comment by skjnldsv** [comment]
@tobiasKaminsky this is a nc13 feature only :)

**Comment by tobiasKaminsky** [comment]
Then we should adapt min-version in info.xml ;-)

**Comment by rullzer** [comment]
Done

**Comment by rullzer** [comment]
Regarding the clipboard thingy lets track that separatly. And somebody with some more js wizzardry should have a look :P

**Comment by tobiasKaminsky** [comment]
Created #6
